Add a null check on profile pic
Bugheist/Flutter pull request #141
Opened 2022-12-13 19:47 UTC by letsintegreat

Closes #140 

I have added a null check on profile pic to save it from crashing. Now it uses a default profile pic in case there is none: ![](https://i.imgur.com/grVOgUA.png)

This is how the app looks like with the default profile pic: 
![Screenshot_1670960833](https://user-images.githubusercontent.com/37345795/207429965-889157c5-9848-46d6-9d8f-4b2e37a41fc5.png)

2022-12-13 19:52 UTC, fredfalcon requested changes
Can you add the image to assets please?

2022-12-13 19:55 UTC, letsintegreat commented
> Can you add the image to assets please?

Yes, that makes more sense. On it

2022-12-18 09:19 UTC, letsintegreat commented
> Can you add the image to assets please?

I have addressed this request, please review.

2022-12-23 13:58 UTC, fredfalcon approved these changes

2022-12-23 13:58 UTC, merged