Add authentication Apis
Bugheist/Flutter pull request #64
Opened 2021-06-22 14:25 UTC by ankit2001

This is an in progress PR for adding all authentication APIs in the frontend. 
Currently working on it.

2021-06-22 14:36 UTC, souravbadami requested changes

2021-06-22 14:36 UTC, souravbadami commented on lib/providers/auth.dart
> +// class AuthProvider with ChangeNotifier {
Please remove these comments. We can recover it back from git anyways.

2021-06-22 19:37 UTC, fredfalcon requested changes
Can you please fix these:

$ flutter "analyze"
Downloading Material fonts...                                      722ms
Downloading Gradle Wrapper...                                       16ms
Downloading package sky_engine...                                  149ms
Downloading flutter_patched_sdk tools...                           361ms
Downloading flutter_patched_sdk_product tools...                   339ms
Downloading darwin-x64 tools...                                  2,921ms
Downloading libimobiledevice...                                     26ms
Downloading usbmuxd...                                              13ms
Downloading libplist...                                             12ms
Downloading openssl...                                             189ms
Downloading ios-deploy...                                           13ms
Downloading darwin-x64/font-subset tools...                        266ms
Running "flutter pub get" in git...                                16.5s
Analyzing git...                                                
  error • 3 positional argument(s) expected, but 2 found • lib/pages/login.dart:74:23 • not_enough_positional_arguments
  error • The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type • lib/providers/auth.dart:130:12 • body_might_complete_normally
   info • The value of the local variable 'response' isn't used • lib/providers/auth.dart:134:14 • unused_local_variable
  error • The await expression can only be used in an async function • lib/providers/auth.dart:134:25 • await_in_wrong_context
   info • Name non-constant identifiers using lowerCamelCase • lib/providers/auth.dart:165:16 • non_constant_identifier_names
  error • The method 'get' isn't defined for the type 'Response' • lib/providers/auth.dart:168:22 • undefined_method
6 issues found. (ran in 21.8s)
flutter analyze found errors: exit status 1

2021-06-23 08:33 UTC, ankit2001 commented on lib/providers/auth.dart
> +// class AuthProvider with ChangeNotifier {
Resolved

2021-06-23 08:58 UTC, ankit2001 commented
> Can you please fix these:
> 
> $ flutter "analyze"
> Downloading Material fonts... 722ms
> Downloading Gradle Wrapper... 16ms
> Downloading package sky_engine... 149ms
> Downloading flutter_patched_sdk tools... 361ms
> Downloading flutter_patched_sdk_product tools... 339ms
> Downloading darwin-x64 tools... 2,921ms
> Downloading libimobiledevice... 26ms
> Downloading usbmuxd... 13ms
> Downloading libplist... 12ms
> Downloading openssl... 189ms
> Downloading ios-deploy... 13ms
> Downloading darwin-x64/font-subset tools... 266ms
> Running "flutter pub get" in git... 16.5s
> Analyzing git...
> error • 3 positional argument(s) expected, but 2 found • lib/pages/login.dart:74:23 • not_enough_positional_arguments
> error • The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type • lib/providers/auth.dart:130:12 • body_might_complete_normally
> info • The value of the local variable 'response' isn't used • lib/providers/auth.dart:134:14 • unused_local_variable
> error • The await expression can only be used in an async function • lib/providers/auth.dart:134:25 • await_in_wrong_context
> info • Name non-constant identifiers using lowerCamelCase • lib/providers/auth.dart:165:16 • non_constant_identifier_names
> error • The method 'get' isn't defined for the type 'Response' • lib/providers/auth.dart:168:22 • undefined_method
> 6 issues found. (ran in 21.8s)
> flutter analyze found errors: exit status 

I fixed this

2021-06-23 09:01 UTC, ankit2001 commented
@fredfalcon, Login API call is successfully working now, I have logged in through the App using the localhost endpoints.

2021-06-23 17:15 UTC, fredfalcon requested changes
please update to staging https://bugheist-staging.herokuapp.com/

2021-06-23 17:15 UTC, fredfalcon commented on lib/util/app_url.dart
> +  static const String testBaseURL = "http://127.0.0.1:8000";
```suggestion
  static const String testBaseURL = "https://bugheist-staging.herokuapp.com/";
```

2021-06-26 17:16 UTC, spiderxm commented on lib/pages/login.dart
> +            print(response['user']);
@ankit2001 print statement is not required. We can remove it. Else it will be visible in app log which is not safe.

2021-06-26 17:18 UTC, spiderxm commented on lib/providers/auth.dart
> +      var accessToken = responseData['key'];
```dart
 var accessToken = responseData['key'];
```
as `accessToken` is not being manipulated it can be changed to 

```dart
 const accessToken = responseData['key'];
````

2021-06-29 13:47 UTC, merged