ADD search field and fix #51
Bugheist/Flutter pull request #73
Opened 2021-08-14 17:23 UTC by ankit2001

This PR aims to add a search bar in the APP and fixing issue #51.

Please review it @souravbadami, @fredfalcon.
Thanks

2022-03-13 02:58 UTC, fredfalcon requested changes
This is not working right.  When I click search it brings me to the detail of the first issue.  This is supposed to search all issues and display a list of results.

2022-03-13 02:58 UTC, fredfalcon commented
Also after it's clicked the bottom nav bar doesn't work anymore.

2022-03-19 12:29 UTC, ankit2001 commented
Will check it as well. Might be again some version error for crashing.

2022-03-26 19:28 UTC, fredfalcon requested changes

2022-03-26 19:28 UTC, fredfalcon commented on lib/pages/home.dart
> +        await get(Uri.parse('https://www.bugheist.com/api/v1/issues/'));
please use the url from the constants file

2022-03-26 19:28 UTC, fredfalcon commented on lib/pages/home.dart
> +      //print(tempList[i]);
remove any comments

2022-04-12 14:43 UTC, fredfalcon commented
@ankit2001 can you please update this to work ?

2022-04-13 05:03 UTC, ankit2001 commented
> 

Sure, will fix all changes, this week.

2022-06-25 16:35 UTC, closed without merging